app/blueprints/auth.py
from flask import render_template, url_for, flash, redirect, request, Blueprint
from app import bcrypt, db
from flask_login import login_user, current_user, logout_user
from app.models import User
from app.forms import RegistrationForm, LoginForm, ResetPasswordForm, RequestResetForm
from app.hundlers import send_reset_email

auth_bp = Blueprint('auth', __name__)

@auth_bp.route("/register", methods=["GET", "POST"])
def register():
    if current_user.is_authenticated:
        return redirect(url_for("main.home"))
    form = RegistrationForm()
    # Check if there are any users in the database
    first_user = User.query.first()
    # Set is_admin to True if this is the first user, otherwise False
    is_admin_status = True if first_user is None else False
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode(
            "utf-8"
        )
        user = User(
            fname=form.fname.data,
            lname=form.lname.data,
            username=form.username.data,
            email=form.email.data,
            password=hashed_password,
            gender = form.gender.data,
            home_address = form.home_address.data,
            phone_number = form.phone_number.data,
            is_admin=is_admin_status
        )
        db.session.add(user)
        db.session.commit()
        flash(f"Account created successfully for {form.username.data}", "success")
        return redirect(url_for("auth.login"))
    return render_template("register.html", title="Register", form=form)


@auth_bp.route("/login", methods=["GET", "POST"])
def login():
    if current_user.is_authenticated:
        return redirect(url_for("main.home"))
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            # If the user is banned, prevent login and flash a message.
            if user.is_banned:
                flash("Your account has been banned. Please contact support for more information.", "danger")
                return redirect(url_for("auth.login"))
            # Successful login: reset failed attempts
            user.failed_login_attempts = 0
            db.session.commit()
            login_user(user, remember=form.remember.data)
            next_page = request.args.get('next')
            flash("You have been logged in!", "success")
            return redirect(next_page) if next_page else redirect(url_for("main.home"))
        else:
            # Failed login attempt
            user = User.query.filter_by(email=form.email.data).first()
            if user:
                user.failed_login_attempts += 1
                if user.failed_login_attempts >= 3:
                    user.is_banned = True
                    flash("Too many failed login attempts. Your account has been banned.", "danger")
                else:
                    flash("Login Unsuccessful. Please check credentials", "danger")
                db.session.commit()
            else:
                flash("Login Unsuccessful. Please check credentials", "danger")
    return render_template("login.html", title="Login", form=form)


@auth_bp.route("/logout")
def logout():
    logout_user()
    return redirect(url_for("main.home"))


@auth_bp.route("/reset_request", methods=["GET", "POST"])
def reset_request():
    form = RequestResetForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user:
            send_reset_email(user)
        flash(
            "If this account exists, you will receive an email with instructions","info")
        return redirect(url_for("auth.login"))
    return render_template("reset_request.html", title="Reset Password", form = form)


@auth_bp.route('/reset_password/<token>', methods=['GET', 'POST'])
def reset_password(token):
    user = User.verify_reset_token(token)
    if not user:
        flash("The token is invalid or expired", "warning")
        return redirect(url_for("auth.reset_request"))
    form = ResetPasswordForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode(
            "utf-8"
        )
        user.password = hashed_password
        db.session.commit()
        flash(f"Your password has been updated. You can now log in", "success")
        return redirect(url_for("auth.login"))
    return render_template("reset_password.html", title="Reset Password", form=form)

app/blueprints/main.py
from flask import render_template, request, redirect, url_for, flash, Blueprint
from flask_login import login_required, current_user, logout_user
from app.models import Product, Newsletter, User, Review, Order
from app.forms import NewsletterForm, UpdateProfileForm, UpdatePasswordForm, DeleteAccountForm
from app import db, bcrypt
from app.utils import save_picture
from sqlalchemy import func
from datetime import datetime, timedelta
from app.utils import get_client_of_the_week


main_bp = Blueprint('main', __name__)


@main_bp.route("/")
@main_bp.route("/home")
def home():
    featureds_products = Product.query.order_by(Product.price.desc()).limit(4).all()
    random_reviews = Review.query.order_by(func.random()).limit(5).all()
    client_of_the_week = get_client_of_the_week()
    return render_template("home.html", featureds=featureds_products, reviews=random_reviews, client_of_the_week=client_of_the_week)

@main_bp.route("/about")
def about():
    return render_template("about.html", title="About")

@main_bp.route("/profile/<string:username>")
def profile(username):
    user = User.query.filter_by(username=username).first_or_404()
    products = Product.query.filter_by(uploader=user).order_by(Product.id.desc()).all()
    return render_template("profile.html", title=f"{user.username}'s Profile", user=user, products=products)

@main_bp.route("/account", methods=["GET", "POST"])
@login_required
def account_settings():
    update_profile_form = UpdateProfileForm()
    update_password_form = UpdatePasswordForm()
    delete_account_form = DeleteAccountForm()

    if request.method == "POST":
        if update_profile_form.submit_profile.data and update_profile_form.validate_on_submit():
            if update_profile_form.picture.data:
                picture_file = save_picture(update_profile_form.picture.data, "static/media/user_pics", output_size=(150, 150))
                current_user.image_file = picture_file
            current_user.fname = update_profile_form.fname.data
            current_user.lname = update_profile_form.lname.data
            current_user.username = update_profile_form.username.data
            current_user.email = update_profile_form.email.data
            current_user.bio = update_profile_form.bio.data
            current_user.phone_number = update_profile_form.phone_number.data
            current_user.gender = update_profile_form.gender.data
            current_user.home_address = update_profile_form.home_address.data
            db.session.commit()
            flash("Your profile has been updated!", "success")
            return redirect(url_for('main.account_settings'))

        elif update_password_form.submit_password.data and update_password_form.validate_on_submit():
            if not bcrypt.check_password_hash(current_user.password, update_password_form.current_password.data):
                flash("Incorrect current password.", "danger")
            else:
                hashed_password = bcrypt.generate_password_hash(update_password_form.new_password.data).decode("utf-8")
                current_user.password = hashed_password
                db.session.commit()
                flash("Your password has been updated!", "success")
            return redirect(url_for('main.account_settings'))

        elif delete_account_form.submit_delete.data and delete_account_form.validate_on_submit():
            if not bcrypt.check_password_hash(current_user.password, delete_account_form.password.data):
                flash("Incorrect password. Account not deleted.", "danger")
            else:
                user_to_delete = User.query.get(current_user.id)
                logout_user()
                if user_to_delete:
                    db.session.delete(user_to_delete)
                    db.session.commit()
                    flash("Your account has been permanently deleted.", "success")
                    return redirect(url_for('main.home'))
                else:
                    flash("An error occurred. User not found.", "danger")

    elif request.method == "GET":
        update_profile_form.fname.data = current_user.fname
        update_profile_form.lname.data = current_user.lname
        update_profile_form.username.data = current_user.username
        update_profile_form.email.data = current_user.email
        update_profile_form.gender.data = current_user.gender
        update_profile_form.home_address.data = current_user.home_address
        update_profile_form.phone_number.data = current_user.phone_number
        update_profile_form.bio.data = current_user.bio

    image_file = url_for("static", filename=f"media/{current_user.image_file}") if current_user.image_file else url_for('static', filename='default.png')

    return render_template("account.html",
                           title="Account Settings",
                           update_profile_form=update_profile_form,
                           update_password_form=update_password_form,
                           delete_account_form=delete_account_form,
                           image_file=image_file)

@main_bp.route("/newsletter_subscribe", methods=["POST"])
def newsletter_subscribe():
    form = NewsletterForm()
    if form.validate_on_submit():
        email = form.email.data
        existing_subscriber = Newsletter.query.filter_by(email=email).first()
        if existing_subscriber:
            flash("You are already subscribed to our newsletter!", "info")
        else:
            subscriber = Newsletter(email=email)
            db.session.add(subscriber)
            db.session.commit()
            flash("Thank you for subscribing to our newsletter!", "success")
    else:
        for field, errors in form.errors.items():
            for error in errors:
                flash(f"Error in {field}: {error}", "danger")

    return redirect(request.referrer or url_for('main.home'))

app/blueprints/products.py
from flask import render_template, request, Blueprint, jsonify
from flask_login import current_user, login_required
from app import db
from app.models import Product, Category, User, Review

products_bp = Blueprint('products', __name__)

@products_bp.route("/products")
def products():
    page = request.args.get('page', 1, type=int)
    category_id = request.args.get('category', type=int)
    min_price = request.args.get('min_price', type=float)
    max_price = request.args.get('max_price', type=float)
    sort_by = request.args.get('sort_by', 'date_desc')

    query = Product.query
    if category_id:
        query = query.filter_by(category_id=category_id)
    if min_price is not None:
        query = query.filter(Product.price >= min_price)
    if max_price is not None:
        query = query.filter(Product.price <= max_price)

    if sort_by == 'price_asc':
        query = query.order_by(Product.price.asc())
    elif sort_by == 'price_desc':
        query = query.order_by(Product.price.desc())
    else: # Default to date (id)
        query = query.order_by(Product.id.desc())

    per_page = 16
    products = query.paginate(page=page, per_page=per_page)
    categories = Category.query.all()
    return render_template("products.html", products=products, categories=categories, sort_by=sort_by,title = "PRODUCTS")

@products_bp.route("/product/<int:product_id>")
def product_detail(product_id):
    product = Product.query.get_or_404(product_id)
    return render_template("product_detail.html", product=product)

@products_bp.route("/products/user/<int:user_id>")
def user_products(user_id):
    user = User.query.get_or_404(user_id)
    products = Product.query.filter_by(uploader=user).all()
    return render_template("user_products.html", products=products, user=user)

@products_bp.route("/products/search", methods=["POST"])
def search_products():
    search_term = request.form.get("search", "")
    if search_term:
        products = Product.query.filter(Product.name.ilike(f"%{search_term}%")).all()
    else:
        products = Product.query.all()
    return render_template("_search_results.html", products=products)

@products_bp.route("/product/<int:product_id>/add_review", methods=["POST"])
@login_required
def add_review(product_id):
    product = Product.query.get_or_404(product_id)
    data = request.get_json()
    rating = data.get('rating')
    text = data.get('text')

    if not rating or not text:
        return jsonify({"error": "Rating and text are required."}), 400

    review = Review(
        rating=rating,
        text=text,
        user_id=current_user.id,
        product_id=product.id
    )
    db.session.add(review)
    db.session.commit()

    return jsonify({
        "id": review.id,
        "rating": review.rating,
        "text": review.text,
        "created_at": review.created_at.strftime("%Y-%m-%d %H:%M:%S"),
        "author": {
            "username": current_user.username
        }
    }), 201

app/templates/_search_results.html
<div class="row" id="product-grid">
    {% for product in products %}
    <div class="col-md-4 mb-4">
        <div class="card">
            <img src="{{ url_for('static', filename='media/product_images/' + product.image_url) if product.image_url else url_for('static', filename='media/product_images/default.png') }}" class="card-img-top" alt="{{ product.name }}">
            <div class="card-body">
                <h5 class="card-title"><a href="{{ url_for('products.product_detail', product_id=product.id) }}">{{ product.name }}</a></h5>
                <p class="card-text">{{ product.description[:100] }}...</p>
                <p class="card-text"><strong>Price:</strong> ${{ product.price }}</p>
                <a href="#" class="btn btn-primary">Add to Cart</a>
            </div>
        </div>
    </div>
    {% endfor %}
</div>

app/templates/about.html
{%extends "layout.html"%} {% block content%}
<div class="container">
  <h1>Hey , This is @About page</h1>
  <hr />
  <h4>
    " Lorem ipsum dolor sit amet consectetur adipisicing elit. Neque quidem
    nihil dolor officiis at magni! "
  </h4>
</div>
{% endblock content %}

app/templates/home.html
{%extends "layout.html"%} {% block content%}
<main class="container">
  <div class="bg-body-tertiary p-5 rounded">
    <h1
      class="typewrite"
      data-period="2000"
      data-type='[ "HI", "GUTEN TAG", " OLÂ ", "SALAAM "," MARHABA", "BONJOUR " , "こんにちは" ]'
    ></h1>
    <br />

    <hr />
    <p class="lead">
      " Lorem ipsum dolor sit amet consectetur adipisicing elit. Neque quidem
      nihil dolor officiis at magni! "
    </p>
    <a
      class="btn btn-lg btn-primary"
      href="{{ url_for('products.products') }}"
      role="button"
      >View All Products
    </a>
  </div>

  {% if client_of_the_week %}
  <div class="alert alert-info text-center my-4" role="alert">
    <h4 class="alert-heading">🌟 Client of the Week! 🌟</h4>
    <p>
      A big thank you to <strong>{{ client_of_the_week.username }}</strong> for
      being our top customer this week!
    </p>
  </div>
  {% endif %}

  <div
    class="hero-section d-flex flex-column align-items-center justify-content-center text-center"
  >
    <h1 class="display-3 fw-bold">E-commerce Web Application (Flask)</h1>
    <p class="lead mt-3">
      This is an e-commerce web application built using the Flask microframework
      in Python. It incorporates several key technologies for its backend and
      basic frontend structure.
    </p>
    <a
      href="{{ url_for('products.products') }}"
      class="btn btn-lg btn-light mt-4"
      >Shop Now</a
    >
  </div>

  <div class="container my-5">
    <h2 class="text-center mb-4 text-dark-pink">Featured Products</h2>
    <div class="row row-cols-1 row-cols-md-3 g-4">
      {% for featured in featureds %}
      <div class="col">
        <div class="card h-100 shadow-sm">
          {% if featured.image_file %}
          <img
            src="{{ url_for('static', filename='media/product_images/' + featured.image_file) }}"
            class="card-img-top product-card-img"
            alt="{{ featured.name }}"
          />
          {% else %}
          <img
            src="{{ url_for('static', filename='media/product_images/default.png') }}"
            class="card-img-top product-card-img"
            alt="{{ featured.name }}"
          />
          {% endif %}
          <div class="card-body">
            <h5 class="card-title">
              <a
                href="{{ url_for('products.product_detail', product_id=featured.id) }}"
                >{{ featured.name }}</a
              >
            </h5>
            <p class="card-text text-muted">${{ featured.price }}</p>
            <button
              class="btn btn-dark-pink text-white add-to-cart-btn"
              data-product-id="{{ featured.id }}"
            >
              Add to Cart
            </button>
          </div>
        </div>
      </div>
      {% endfor %}
    </div>

    <hr />

    <div class="container my-5 text-center">
      <h2 class="mb-4 text-dark-pink">What Our Customers Say</h2>
      {% if reviews %}
      <div class="row">
        <div class="col-md-8 offset-md-2">
          <div
            id="testimonialCarousel"
            class="carousel slide"
            data-bs-ride="carousel"
          >
            <div class="carousel-inner">
              {% for review in reviews %}
              <div class="carousel-item {% if loop.first %}active{% endif %}">
                <p class="fs-5">"{{ review.text }}"</p>
                <p class="fw-bold">- {{ review.author.username }}</p>
                <p class="text-muted">Rating: {{ review.rating }}/5</p>
              </div>
              {% endfor %}
            </div>
            <button
              class="carousel-control-prev"
              type="button"
              data-bs-target="#testimonialCarousel"
              data-bs-slide="prev"
            >
              <span
                class="carousel-control-prev-icon"
                aria-hidden="true"
              ></span>
              <span class="visually-hidden">Previous</span>
            </button>
            <button
              class="carousel-control-next"
              type="button"
              data-bs-target="#testimonialCarousel"
              data-bs-slide="next"
            >
              <span
                class="carousel-control-next-icon"
                aria-hidden="true"
              ></span>
              <span class="visually-hidden">Next</span>
            </button>
          </div>
        </div>
      </div>
      {% else %}
      <p>No reviews yet. Be the first to leave a review!</p>
      {% endif %}
    </div>

    <hr />
  </div>
</main>
{% endblock content %}

app/templates/layout.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <meta
      name="description"
      content="A brief and compelling description of your page content."
    />
    <meta name="keywords" content="keyword1, keyword2, keyword3" />
    <meta name="author" content="Ghassen Ben Taher" />
    <meta property="og:title" content="Your Store" />
    <meta
      property="og:description"
      content="I Never thought I'd be a programmer without sight, but with little help from my trusty screen reader and a whole lot of caffeine. here I am!"
    />
    <meta property="og:url" content="https://www.bentaherghassen.com" />
    <meta property="og:type" content="website" />
    <meta name="twitter:card" content="summary_large_image" />
    <meta name="twitter:site" content="@bentaherghassen" />
    <meta name="twitter:creator" content="@bentaherghassen" />
    <meta name="twitter:title" content="Your Store" />
    <meta
      name="twitter:description"
      content="I Never thought I'd be a programmer without sight, but with little help from my trusty screen reader and a whole lot of caffeine. here I am!"
    />
    <meta
      name="twitter:image"
      content="https://www.bentaherghassen.com/image.jpg"
    />
    <meta name="twitter:domain" content="https://www.bentaherghassen.com" />
    <meta name="robots" content="index, follow" />
    <meta
      name="google-site-verification"
      content="your-google-verification-code"
    />
    <meta name="copyright" content="Copyright © Ghassen Ben Taher" />
    {% if title %}
    <title>AppName- {{title}} Page</title>
    {% else %}
    <title>AppName</title>
    {%endif%}

    <link rel="shortcut icon" href="favicon.ico" type="image/x-icon" />
    <link
      rel="stylesheet"
      href="{{ url_for('static', filename='css/main.css') }}"
    />
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH"
      crossorigin="anonymous"
    />
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link
      href="https://fonts.googleapis.com/css2?family=Ubuntu:wght@400;700&display=swap"
      rel="stylesheet"
    />
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/css/all.min.css"
    />
    <script
      src="https://unpkg.com/htmx.org@2.0.4"
      integrity="sha384-HGfztofotfshcF7+8n44JQL2oJmowVChPTg48S+jvZoztPfvwD79OC/LTtG6dMp+"
      crossorigin="anonymous"
    ></script>
  </head>

  <body class="d-flex flex-column min-vh-100">
    <nav class="navbar navbar-expand-lg navbar-light bg-pink fixed-top">
      <div class="container-fluid">
        <a
          class="navbar-brand text-white fw-bold"
          href="{{ url_for('main.home') }}"
          >Your Store</a
        >
        <button
          class="navbar-toggler"
          type="button"
          data-bs-toggle="collapse"
          data-bs-target="#navbarCollapse"
          aria-controls="navbarCollapse"
          aria-expanded="false"
          aria-label="Toggle navigation"
        >
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarCollapse">
          <ul class="navbar-nav me-auto mb-2 mb-md-0">
            <li class="nav-item">
              <a
                class="nav-link active text-white"
                aria-current="page"
                href="{{ url_for('main.home') }}"
                >Home</a
              >
            </li>
            <li class="nav-item">
              <a class="nav-link text-white" href="{{ url_for('main.about') }}"
                >About</a
              >
            </li>
          </ul>
          <div class="d-flex align-items-center me-3">
            <span
              class="navbar-text"
              style="color: {{ store_status_color }}; font-weight: bold;"
            >
              We are: {{ store_status }}
            </span>
          </div>
          <div class="d-flex me-3">
            <input
              class="form-control me-2"
              type="search"
              name="search"
              placeholder="Search for products..."
              hx-post="/products/search"
              hx-trigger="keyup changed delay:500ms"
              hx-target="#product-grid"
              hx-swap="innerHTML"
            />
          </div>
          <div class="d-flex align-items-center">
            <a
              href="{{ url_for('orders.cart') }}"
              class="nav-link fw-bold py-1 px-0 me-3 text-white"
            >
              Cart
              <span id="cart-counter" class="badge bg-success"
                >{{ cart_count }}</span
              >
            </a>
            {% if current_user.is_authenticated and current_user.is_admin %}
            <li class="nav-item">
              <a class="nav-link text-white" href="{{ url_for('admin.users') }}"
                >Dashboard</a
              >
            </li>
            {% endif %} {% if current_user.is_authenticated %}
            <div class="nav-item dropdown">
              <a
                class="nav-link dropdown-toggle text-white"
                href="#"
                id="navbarDropdown"
                role="button"
                data-bs-toggle="dropdown"
                aria-expanded="false"
              >
                {{ current_user.fname }}
              </a>
              <ul
                class="dropdown-menu dropdown-menu-end"
                aria-labelledby="navbarDropdown"
              >
                <li>
                  <a
                    class="dropdown-item"
                    href="{{ url_for('main.profile', username=current_user.username) }}"
                    >Profile</a
                  >
                </li>
                <li>
                  <a
                    class="dropdown-item"
                    href="{{ url_for('orders.order_history', username=current_user.username) }}"
                    >Orders</a
                  >
                </li>
                <li>
                  <a
                    class="dropdown-item"
                    href="{{ url_for('main.account_settings') }}"
                    >Account Settings</a
                  >
                </li>
                <li class="nav-item d-flex align-items-center me-3">
                  <div class="form-check form-switch">
                    <input
                      class="form-check-input"
                      type="checkbox"
                      role="switch"
                      id="mode-toggle"
                    />
                    <label class="form-check-label text-white" for="mode-toggle"
                      >Dark Mode</label
                    >
                  </div>
                </li>

                <li><hr class="dropdown-divider" /></li>

                <li>
                  <a class="dropdown-item" href="{{ url_for('auth.logout') }}"
                    >Logout</a
                  >
                </li>
              </ul>
            </div>
            {% else %}
            <a
              href="{{ url_for('auth.login') }}"
              class="nav-link text-white me-3"
              ><i class="fas fa-user"></i> Login</a
            >
            <a
              href="{{ url_for('auth.register') }}"
              class="nav-link text-white me-3"
              >Register</a
            >
            {% endif %}
          </div>
        </div>
      </div>
    </nav>
    <div id="toast-notification" class="toast-notification">
      Product added to cart!
    </div>
    {% with messages = get_flashed_messages(with_categories=true) %} {% if
    messages %} {% for category, message in messages %}
    <div class="alert alert-{{category}} text-center">{{message}}</div>
    {% endfor %} {% endif %} {% endwith %} {% block content%} {% endblock %}

    <footer class="bg-dark text-white py-5 mt-auto">
      <div class="container">
        <div class="row">
          <div class="col-md-3">
            <h5 class="fw-bold">Your Store</h5>
            <p>Fashion for a better you.</p>
            <div class="d-flex">
              <a
                href="https://www.bentaherghassen.com"
                class="text-white me-3"
                target="_blank"
                ><i class="fab fa-facebook fa-2x"></i
              ></a>
              <a
                href="https://www.bentaherghassen.com"
                class="text-white me-3"
                target="_blank"
                ><i class="fab fa-twitter fa-2x"></i
              ></a>
              <a
                href="https://www.bentaherghassen.com"
                class="text-white me-3"
                target="_blank"
                ><i class="fab fa-instagram fa-2x"></i
              ></a>
            </div>
          </div>
          <div class="col-md-3">
            <h5 class="fw-bold">Quick Links</h5>
            <ul class="list-unstyled">
              <li>
                <a
                  href="https://www.bentaherghassen.com"
                  class="text-white text-decoration-none"
                  >About Us</a
                >
              </li>
              <li>
                <a
                  href="https://www.bentaherghassen.com"
                  class="text-white text-decoration-none"
                  >Contact Us</a
                >
              </li>
              <li>
                <a
                  href="https://www.bentaherghassen.com"
                  class="text-white text-decoration-none"
                  >FAQs</a
                >
              </li>
            </ul>
          </div>
          <div class="col-md-3">
            <h5 class="fw-bold">Legal</h5>
            <ul class="list-unstyled">
              <li>
                <a
                  href="https://www.bentaherghassen.com"
                  class="text-white text-decoration-none"
                  >Privacy Policy</a
                >
              </li>
              <li>
                <a
                  href="https://www.bentaherghassen.com"
                  class="text-white text-decoration-none"
                  >Terms of Service</a
                >
              </li>
              <li>
                <a
                  href="https://www.bentaherghassen.com"
                  class="text-white text-decoration-none"
                  >Shipping Info</a
                >
              </li>
            </ul>
          </div>

          <div class="col-md-3">
            <h5 class="fw-bold">Newsletter</h5>
            <p>Sign up to get the latest deals.</p>
            <form
              method="POST"
              action="{{ url_for('main.newsletter_subscribe') }}"
            >
              {{ newsletter_form.hidden_tag() }}
              <div class="input-group mb-3">
                {{ newsletter_form.email(class="form-control",
                placeholder="Email Address", required=True) }} {{
                newsletter_form.submit(class="btn btn-dark-pink text-white") }}
              </div>
            </form>
          </div>
        </div>
        <div class="text-center pt-4 mt-4 border-top">
          <p>
            &copy; 2020-<span id="current-year"></span> Your Store. All Rights
            Reserved.
          </p>
        </div>
      </div>
    </footer>

    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
      crossorigin="anonymous"
    ></script>
    <script src="{{ url_for('static', filename='js/dark_mode_switch.js') }}"></script>
    <script src="{{ url_for('static', filename='js/current_date.js') }}"></script>
    <script src="{{ url_for('static', filename='js/cart_count.js') }}"></script>
    <script src="{{ url_for('static', filename='js/main.js') }}"></script>
    <script src="https://unpkg.com/htmx.org@1.9.10"></script>
    <script src="{{ url_for('static', filename='js/text_moving.js') }}"></script>
    <script src="{{ url_for('static', filename='js/htmx.min.js') }}"></script>
    {% block scripts %}{% endblock %}
  </body>
</html>